<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="MAIN" Id="{08a38933-7d15-4d08-a1e8-48039f2428b0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	text : STRING[30] := 'hello';
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>